Add void to functions in C missing parameters to fix -Wstrict-prototypes warnings.
This warning became more strict after updates in the clang compiler.

The error message that this change fixes is:

```
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
```
PiperOrigin-RevId: 472723024