[.kokoro] Upgrade bazel prior to checking dependencies. (#6106)
The scripts/affected_targets script was not returning the expected targets on kokoro, but it was doing so locally. It was failing on kokoro because the default bazel install on kokoro is 0.11, but we rely on 0.20 in order to be able to run bazel query.

This change upgrades the bazel version to 0.20 prior to checking the affected targets.

I tested the failure by adding the following command to https://github.com/material-components/material-components-ios/pull/6101

```
bazel query --universe_scope=//... --order_output=no "kind(test, allrdeps('components/Buttons/src/private/MDCButton+Subclassing.h'))"
```

Which generated the following error output:

```
ERROR: error loading package 'components/PageControl': Extension file not found. Unable to load package for '@bazel_tools//tools/build_defs/cc:action_names.bzl': BUILD file not found on package path
```